apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive-clone-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drive-clone-service-selector
  template:
    metadata:
      labels:
        app: drive-clone-service-selector
    spec:
      containers:
        - name: nextjs-container
          image: imshubhamj/meow:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: drive-clone-service-selector
  type: LoadBalancer # External Service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30000 # External Service PORT (30000 - 32767)
